// gen-samples.js — generate rich, ≥2000-char interview SAMPLES (resume + JD +
// multi-turn transcript) in the interview-samples.js shape, for the new-interview
// modal. Diverse roles/languages. Prints a JS module to stdout.
//
// Usage: DASHSCOPE_TRANSPORT=curl node prompt-training/gen-samples.js > /tmp/samples.js

const fs = require('fs');
const path = require('path');
const { dashscopeChat, safeJsonParse, FLASH_MODEL } = require('../src/main-process/features/interviewer/expert-orchestrator');

function key() {
  if (process.env.DASHSCOPE_API_KEY) return process.env.DASHSCOPE_API_KEY.trim();
  try { return String(JSON.parse(fs.readFileSync(path.join(process.cwd(), 'cache', 'app-state.json'), 'utf8')).dashscopeApiKey || '').trim(); } catch (_) { return ''; }
}

// (id, display name prefix, language, role brief, answer style of the LAST turn)
const SPECS = [
  { id: 'rich-backend-zh', lang: 'Chinese', role: '资深后端 / 分布式系统工程师', style: '具体、有担当但中途踩过坑' },
  { id: 'rich-pm-en', lang: 'English', role: 'Senior Product Manager (B2B SaaS)', style: 'specific with metrics, owns a wrong call' },
  { id: 'rich-ml-mixed', lang: 'mixed Chinese+English technical terms', role: 'ML / 推荐排序工程师', style: '中英混杂，技术深入，承认一次 train-serving skew' },
  { id: 'rich-em-en', lang: 'English', role: 'Engineering Manager (12-person org)', style: 'reflective about a hard people decision' },
  { id: 'rich-sales-zh', lang: 'Chinese', role: '企业级销售 / 大客户 BD', style: '韧性强，复盘一个丢掉的大单' },
  { id: 'rich-data-en', lang: 'English', role: 'Data Scientist (experimentation)', style: 'rigorous, admits an experiment that misled them' }
];

function prompt(spec) {
  return `Author ONE realistic, COHERENT job-interview sample for role: ${spec.role}. Language: ${spec.lang}.
Output STRICT JSON only (no markdown), shape:
{"name":"<short label, prefix with ZH·/EN·/Mixed· per language, <=34 chars>","language":"${spec.lang.includes('mixed') ? 'mixed' : (spec.lang === 'Chinese' ? 'zh' : 'en')}","interviewType":"online","resume":"<250-380 words, concrete: companies, scope, stack, 1-2 quantified wins>","jd":"<150-220 words, what the team cares about + how they evaluate>","turns":[{"speaker":"interviewer","text":"<q1>"},{"speaker":"candidate","text":"<a1>"},{"speaker":"interviewer","text":"<q2>"},{"speaker":"candidate","text":"<a2>"},{"speaker":"interviewer","text":"<q3>"},{"speaker":"candidate","text":"<LONG final answer, 180-260 words, enacting style: ${spec.style}>"}]}
Rules: turns alternate interviewer/candidate, START with interviewer, END with the candidate's LONG answer (the thing to follow up on). The whole sample (resume+jd+all turn texts) MUST total >= 2000 characters. Make it mutually coherent and specific to the role. Emit only the JSON object.`;
}

async function genOne(apiKey, spec) {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const { text } = await dashscopeChat({ apiKey, model: FLASH_MODEL, prompt: prompt(spec), temperature: 0.8, maxTokens: 2600, timeoutMs: 120000, thinking: { type: 'disabled' } });
      const p = safeJsonParse(text);
      if (!p || !p.resume || !Array.isArray(p.turns) || p.turns.length < 4) continue;
      const ctx = (p.resume + p.jd + p.turns.map((t) => t.text || '').join('')).length;
      if (ctx < 2000) continue; // enforce the 2000-char floor
      return {
        id: spec.id,
        name: String(p.name || spec.role).slice(0, 40),
        language: p.language || 'en',
        interviewType: 'online',
        resume: String(p.resume),
        jd: String(p.jd || ''),
        turns: p.turns.map((t) => ({ speaker: t.speaker === 'interviewer' ? 'interviewer' : 'candidate', text: String(t.text || '') })),
        _ctx: ctx
      };
    } catch (_) { /* retry */ }
  }
  return null;
}

async function main() {
  const apiKey = key();
  if (!apiKey) { console.error('No DashScope key'); process.exit(2); }
  const out = [];
  for (const spec of SPECS) {
    const s = await genOne(apiKey, spec);
    if (s) { console.error(`  ${s.id}: ${s._ctx} chars ✓`); delete s._ctx; out.push(s); }
    else console.error(`  ${spec.id}: FAILED`);
  }
  const header = `// Built-in sample interviews for trying out Generate Q without a live transcript.
// Each sample carries a résumé + JD + a multi-turn transcript whose LAST turn is a
// long candidate answer (the thing the interviewer follows up on). Mixed zh/en so
// the copilot can be exercised across languages. Selected in the new-interview
// modal; seedInterviewSample() (renderer.js) injects it. All >= 2000-char context.
//
// Shape: { id, name, language, interviewType, resume, jd,
//          turns: [{ speaker: 'interviewer' | 'candidate', text }] }
//
// Generated by prompt-training/gen-samples.js (DeepSeek). Regenerate to refresh.

export const INTERVIEW_SAMPLES = ${JSON.stringify(out, null, 2)};

export function getInterviewSample(id) {
  return INTERVIEW_SAMPLES.find((s) => s.id === id) || null;
}
`;
  process.stdout.write(header);
}
main().catch((e) => { console.error(e); process.exit(1); });
