import type { OutputLanguage } from '@open-cluely/contract';

interface FollowUpCopy {
  ariaFollowUp: string;
  cardLabel: string;
  suggestedLabel: string;
  alternative: string;
  alternativeShort: string;
  why: string;
  anchoredTo: string;
  expected: string;
  pickedPrefix: string;
  pickCandidateTitle: string;
  triggerAuto: string;
  triggerManual: string;
  triggerAutoTitle: string;
  triggerManualTitle: string;
  rankedSummary: (count: number) => string;
}

const EN_COPY: FollowUpCopy = {
  ariaFollowUp: 'Suggested follow-up',
  cardLabel: 'AI follow-up',
  suggestedLabel: 'Suggested follow-up',
  alternative: 'Alternative',
  alternativeShort: 'Alt',
  why: 'Why ask this',
  anchoredTo: 'Anchored to',
  expected: 'Expected evidence',
  pickedPrefix: 'Selected: ',
  pickCandidateTitle: 'Use this candidate question',
  triggerAuto: 'Auto',
  triggerManual: 'Manual',
  triggerAutoTitle: 'Auto-generated from the live conversation',
  triggerManualTitle: 'Generated by the Generate Q button',
  rankedSummary: (count) => `More ranked candidates (${count})`
};

const ZH_COPY: FollowUpCopy = {
  ariaFollowUp: '建议追问',
  cardLabel: 'AI 追问',
  suggestedLabel: '建议追问',
  alternative: '备选问题',
  alternativeShort: '备选',
  why: '为什么这样问',
  anchoredTo: '依据片段',
  expected: '预期证据',
  pickedPrefix: '已选用：',
  pickCandidateTitle: '选用这个候选问题',
  triggerAuto: '自动',
  triggerManual: '手动',
  triggerAutoTitle: '根据实时对话自动生成',
  triggerManualTitle: '通过 Generate Q 手动生成',
  rankedSummary: (count) => `更多排序候选 (${count})`
};

/**
 * Empty output language means "auto/default"; preserve the mixed legacy UI copy
 * so the explicit language selector is the only behavior switch.
 */
const DEFAULT_COPY: FollowUpCopy = {
  ...EN_COPY,
  pickedPrefix: ZH_COPY.pickedPrefix,
  pickCandidateTitle: ZH_COPY.pickCandidateTitle,
  triggerAuto: ZH_COPY.triggerAuto,
  triggerManual: ZH_COPY.triggerManual,
  rankedSummary: ZH_COPY.rankedSummary
};

export function followUpCopyFor(outputLanguage?: OutputLanguage): FollowUpCopy {
  if (outputLanguage === 'zh') return ZH_COPY;
  if (outputLanguage === 'en') return EN_COPY;
  return DEFAULT_COPY;
}
